using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace LiftBroAPI.Entities
{
    public class Activity    
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string Name { get; set; }
    }
}