using System.Transactions;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace LiftBroAPI.Entities
{
    public class Exercise
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }        public Activity Activity { get; set; }
        public int Repitations { get; set; }
        public int Sets { get; set; }
        public double Weight { get; set; }
    }
}