using System.Collections.Generic;
using System.Reflection.Metadata;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace LiftBroAPI.Entities
{
    public class User
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }        public int Type { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public ICollection<Workout> Workouts { get; set; }
        
    }
}